//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableClassGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableClassGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Use Dapper.Aggregator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllowDapperAggregator {
            get {
                return ResourceManager.GetString("AllowDapperAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User uEN Framework に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllowuENFramework {
            get {
                return ResourceManager.GetString("AllowuENFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllSelect {
            get {
                return ResourceManager.GetString("AllSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompleteMessage {
            get {
                return ResourceManager.GetString("CompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate And Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateAndSave {
            get {
                return ResourceManager.GetString("GenerateAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please put a check mark. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InfomationCheckMark {
            get {
                return ResourceManager.GetString("InfomationCheckMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the auto-generated class. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSaveClass {
            get {
                return ResourceManager.GetString("MessageSaveClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target is {0} tables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectedTables {
            get {
                return ResourceManager.GetString("MessageSelectedTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuestionSave {
            get {
                return ResourceManager.GetString("QuestionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target is not selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarningSelectTarget {
            get {
                return ResourceManager.GetString("WarningSelectTarget", resourceCulture);
            }
        }
    }
}
